# Generated by Django 3.2.18 on 2023-04-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_user_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.CharField(max_length=2000),
        ),
    ]
