# Generated by Django 3.2.18 on 2023-04-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_vendor_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
