# Generated by Django 3.2.18 on 2023-04-17 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_productimages_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='images',
            new_name='image',
        ),
    ]
