# Generated by Django 3.2.18 on 2023-04-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_images_productimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.IntegerField(blank=True, default=100, max_length=9999, null=True),
        ),
    ]
