# Generated by Django 3.2.18 on 2023-04-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_stock_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_count',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
