# Generated by Django 3.2.18 on 2023-04-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_shippingaddress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
