# Generated by Django 3.2.18 on 2023-04-22 08:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20230420_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='This is product!!!', null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='descripton',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
