# Generated by Django 3.2.18 on 2023-04-23 13:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20230422_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proudcutreview',
            options={'verbose_name_plural': 'ProductReviews'},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='This is product!!!', null=True),
        ),
        migrations.AlterField(
            model_name='proudcutreview',
            name='rating',
            field=models.CharField(choices=[('', 'Chose the score'), ('1', '★✰✰✰✰'), ('2', '★★✰✰✰'), ('3', '★★★✰✰'), ('4', '★★★★✰'), ('5', '★★★★★')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='descripton',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
