# Generated by Django 3.2.18 on 2023-04-23 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_proudcutreview_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proudcutreview',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='store.product'),
        ),
    ]
