# Generated by Django 3.2.18 on 2023-04-24 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_proudcutreview_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProudcutReview',
            new_name='ProuductReview',
        ),
    ]
