# Generated by Django 3.2.18 on 2023-04-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_rename_proudcutreview_prouductreview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProuductReview',
            new_name='ProductReview',
        ),
    ]
