# Generated by Django 3.2.18 on 2023-06-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
    ]
