# Generated by Django 3.2.18 on 2023-06-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_shippingaddress_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='user',
        ),
    ]
