# Generated by Django 3.2.18 on 2023-06-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_shippingaddress_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
