# Generated by Django 3.2.18 on 2023-06-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_shippingaddress_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_status',
            field=models.CharField(blank=True, default='ok', max_length=200, null=True),
        ),
    ]
