# Generated by Django 3.2.18 on 2023-06-17 16:11

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_auto_20230617_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to=store.models.user_directory_path),
        ),
    ]
