# Generated by Django 3.2.18 on 2023-07-22 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_auto_20230618_0043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
